site_name: scope-your-project-gruppe-6 – Doku
theme:
  name: material
  language: de
  logo: docs/images/logo.png
  favicon: docs/images/favicon.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - navigation.footer
    - content.action.edit
    - content.action.view

  palette:
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Darkmode aktivieren 🌙
    - scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Lightmode aktivieren ☀️

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Willkommen: index.md
  - Schnellstart: getting_started.md
  - Architektur: architecture.md
  - API: api.md
  - FAQ: faq.md

repo_name: scope-your-project-gruppe-6
repo_url: https://github.com/HSLU-Exercise/scope-your-project-gruppe-6
edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HSLU-Exercise/scope-your-project-gruppe-6
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg
  generator: false
  copyright: "© 2025 Gruppe 6 — HSLU"

plugins:
  - search
  - tags
  - autorefs
