site_name: scope-your-project-gruppe-6 – Doku

theme:
  name: material
  language: de
  logo: logo.png                  # optional: Datei in docs/images/logo.png
  favicon: logo.png            # optional: Datei in docs/images/favicon.png
  features:
    - navigation.instant                 # Seitenwechsel ohne Reload
    - navigation.tabs                    # Tabs in der Hauptnavigation
    - navigation.sections                # Abschnittsweise Struktur
    - search.suggest                     # Suchvorschläge
    - search.highlight                   # Treffer hervorheben
    - content.code.copy                  # Copy-Button für Codeblöcke
    - content.tabs.link                  # Tabs klickbar machen
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dunkelmodus
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Hellmodus

# --- Markdown-Erweiterungen (Buttons, Callouts, Emojis, Tabs, …) ---
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# -------------------------------------------------------------------

# Navigation – nur vorhandene Seiten verlinkt
nav:
  - Willkommen: index.md
  - Schnellstart: getting-started.md
  - Architektur: architecture.md
  - API: api.md
  - FAQ: faq.md

# (Optional) Social-Links im Footer – gerne anpassen/entfernen
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HSLU-Exercise/scope-your-project-gruppe-6
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com       # ggf. Team- oder Projektprofil verlinken

# (Optional) Copyright im Footer – anpassen erlaubt
copyright: "© 2025 Gruppe 6 – HSLU"
