# mkdocs.yml
site_name: scope-your-project-gruppe-6 – Doku
theme:
  name: material
  language: de
  logo: docs/images/logo.png
  favicon: docs/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: blue
      accent: lime
    - scheme: default
      primary: indigo
      accent: blue

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Willkommen: index.md
  - Schnellstart: getting_started.md
  - Architektur: architecture.md
  - API: api.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HSLU-Exercise/scope-your-project-gruppe-6
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
  copyright: © 2025 Gruppe 6 · HSLU
